### PR TITLE
Kazakh pages

### PR DESCRIPTION
**Pull request by kz-userstat**

### CODE REVIEW

**Comment by brockfanning** [comment]
We can close this PR.

**Comment by brockfanning** [comment]
@kz-userstat Correct, this can be closed. Since I am not on the team, I don't have the ability to close pull requests, so you will need to do that.

**Comment by brockfanning** [comment]
@kz-userstat Is there a "Close pull request" button at the bottom? That should work I think.

**Comment by kz-userstat** [comment]
Wow indeed it somehow worked :-)

**Comment by kz-userstat** [comment]
Actually I can't "Merge pull request" since the button is inactive. Instead I have to press Resolve conflicts button and when I try to do something nothing happens

**Comment by kz-userstat** [comment]
изображение
this is picture what I got when I press Resolve conflicts button

**Comment by brockfanning** [comment]
@kz-userstat This pull-request "Kazakh pages" can be closed. You can press "Close pull request" for ths one.

I was referring to the _other_ pull-request to re-open: "Use master branch for production deployment" (#23 )

**Pull request closed without merging**
